format = """
[](#a3aed2)\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#394260 bg:#1d2230)\
$cmd_duration\
$status\
[ ](fg:#1d2230)"""

[character]
disabled = true

[line_break]
disabled = true

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[status]
disabled = false
style = 'bg:#1d2230 fg:#ff0000'
format = '[ (SIG$signal_name)($common_meaning)( \($status\)) ]($style)'

[cmd_duration]
min_time = 15_000
format = '[ $duration ]($style)'
style = 'bg:#1d2230 fg:#769ff0'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
conflicted = '\(conflits\) '
untracked = '\(untracked files\) '
staged = '\(staged\) '
format = '[[($conflicted$untracked$staged)](fg:#769ff0 bg:#394260)]($style)'

[git_metrics]
disabled = false
added_style = 'fg:#00ff00 bg:#394260'
deleted_style = 'fg:#ff0000 bg:#394260'
only_nonzero_diffs = true
format = '([+$added/-$deleted ](fg:#769ff0 bg:#394260))'

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = '[$symbol]($style)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "



